kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: expressapp
spec:
  replicas:
  template:
    metadata:
      name: expressapp
      labels:
        app: expressapp
        role: expressapp
        env: production
    spec:
      containers:
      - name: expressapp
        image: shahzeb799/expressapp:latest
        resources:
          limits:
            memory: "500Mi"
            cpu: "100m"
        imagePullPolicy: Always
        ports:
        - name: expressapp
          containerPort: 3000
