kind: Service
apiVersion: v1
metadata:
  name: expressapp
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: 3000
  externalIPs:
  - 35.196.246.48
  selector:
    app: expressapp
    role: expressapp
